services:
  bulwark.auth.admin:
    image: "lateflip/bulwark.auth.admin:1.0.0-beta.2"
    env_file:
      - .env
    ports:
      - 8080:80
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - 27017:27017